version: '3'
services:
  web:
    container_name: fp_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${RAILS_PORT:-3000} -b '0.0.0.0'"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${RAILS_PORT:-3000}:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

  db:
    container_name: fp_db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "${MYSQL_PORT:-3306}:3306"

  redis:
    image: redis:latest
    container_name: fp_redis
    ports:
      - "6379:6379"

  sidekiq:
    container_name: fp_sidekiq
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis


volumes:
  db-data:
