services:
  app:
    build:
      context: .
      args:
        VARIANT: '3.1-bullseye'
        BUNDLER_VERSION: '2.3.14'
        RAILS_VERSIONS: '7.0.3'
        NODE_VERSION: '16'
    environment:
      BINDING: 0.0.0.0
    volumes:
      - ..:/home/vscode/environment:cached
      - bundle-volume:/usr/local/bundle
    command: sleep infinity

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_development
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  bundle-volume:
  mysql-data:
