default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { 'root' } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("MYSQL_HOST") { 'db' } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { 'fp_app_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { 'fp_app_test' } %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
